project_name: gh

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "GitHub CLI {{.Version}}"

before:
  hooks:
    - make manpages GH_VERSION={{.Version}}

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign-windows-executable.sh '{{ .Path }}'
          output: false
    binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: nix-archive
    builds: [macos, linux]
    name_template: >-
      gh_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}linux{{ end }}_
      {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/gh*.1
  - id: win-archive
    builds: [windows]
    name_template: "gh_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/cli/cli
    bindir: /usr
    dependencies:
      - git
    description: GitHub’s official command line tool.
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/gh*.1"
        dst: "/usr/share/man/man1"
